apiVersion: apps/v1
kind: Deployment
metadata:
  name: gif-app-project
  labels:
    app: gif-app-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gif-app-project
  template:
    metadata:
      labels:
        app: gif-app-project
    spec:
      containers:
      - name: gif-app-project
        image: lidoy/gif-app-project:latest
        ports:
        - containerPort: 5000
        env:
          - name: DB_HOST
            value: "127.0.0.1"
          - name: DB_NAME
            value: "flask-bd"
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db_userdetails
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db_userdetails
                key: password
          - name: cloud-sql-proxy
            image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
            command:
              - "/cloud_sql_proxy"
              - "-instances=flaskproject:us-central1-c:flask-db=tcp:3306"
              - "-credential_file=/secrets/cloudsql/credentials.json"
            volumeMounts:
              - name: cloudsql-instance-credentials
                mountPath: /secrets/cloudsql
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: gif-app-project-service
  labels:
    app: gif-app-project-service
spec:
  type: LoadBalancer
  selector:
    app: gif-app-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000



